In [2]:
import pandas as pd
import numpy as np

In [3]:
pip install konlpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import os
import re

from sklearn import datasets, model_selection
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize, sent_tokenize
from konlpy.tag import Hannanum
from konlpy.tag import Kkma
from konlpy.tag import Okt
import pandas as pd
import numpy as np

In [5]:
path = "C:/Users/ILIFO-034/Desktop/쿠팡/crawling"
folder_list = os.listdir(path)
print(folder_list)

['1.패션의류잡화', '10.자동차용품', '11.도서음반DVD', '12.완구취미', '13.문구오피스', '14.반려동물용품', '15.헬스건강식품', '2.뷰티', '3.출산유아동', '4.식품', '5.주방용품', '6.생활용품', '7.홈인테리어', '8.가전디지털', '9.스포츠레저']


In [6]:
path = "C:/Users/ILIFO-034/Desktop/쿠팡/crawling/"
folder_list = os.listdir(path)

print ("folder_list: {}".format(folder_list))

dd = pd.DataFrame(columns=['대분류','중분류','소분류'])
for k in range(len(folder_list)):
    path = "C:/Users/ILIFO-034/Desktop/쿠팡/crawling/{}".format(folder_list[k])
    file_list = os.listdir(path)
    for j in range(len(file_list)):
        data = pd.read_csv("{}/{}".format(path,file_list[j]))
        split = data.내용.str.split("', ")
        st = []
        for i in split:
          if len(i) >= 10:
            st.append(i)
        split = pd.Series(st)
        split = split.apply(lambda x: pd.Series(x))
        split.stack()
        split.stack().reset_index(level=1, drop=True)
        split = split.stack().reset_index(level=1, drop=True).to_frame('내용')
        dd = pd.concat([dd,data.merge(split, left_index=True, right_index=True, how='left')])

folder_list: ['1.패션의류잡화', '10.자동차용품', '11.도서음반DVD', '12.완구취미', '13.문구오피스', '14.반려동물용품', '15.헬스건강식품', '2.뷰티', '3.출산유아동', '4.식품', '5.주방용품', '6.생활용품', '7.홈인테리어', '8.가전디지털', '9.스포츠레저']


In [7]:
# dd = pd.DataFrame(columns=['대분류','중분류','소분류'])
# for k in range(len(folder_list)):
#     path = "C:/Users/ILIFO-034/Desktop/쿠팡/crawling/{}".format(folder_list[k])
#     file_list = os.listdir(path)
#     for j in range(len(file_list)):
#         data = pd.read_csv("{}/{}".format(path,file_list[j]))
#         print(path,file_list[j])
#         split = data.내용.str.split("', ")
#         st = []
#         try:
#             for i in split:
#                 if len(i) >= 10:
#                     st.append(i)
#             split = pd.Series(st)
#             split = split.apply(lambda x: pd.Series(x))
#             split.stack()
#             split.stackㅌ().reset_index(level=1, drop=True)
#             split = split.stack().reset_index(level=1, drop=True).to_frame('내용')
#             dd = pd.concat([dd,data.merge(split, left_index=True, right_index=True, how='left')])
#         except:
#             pass
       

In [8]:
dd

대분류    중분류      소분류  Unnamed: 0  \
0   패션의류/잡화  가방/잡화     여성가방         0.0   
0   패션의류/잡화  가방/잡화     여성가방         0.0   
0   패션의류/잡화  가방/잡화     여성가방         0.0   
0   패션의류/잡화  가방/잡화     여성가방         0.0   
0   패션의류/잡화  가방/잡화     여성가방         0.0   
..      ...    ...      ...         ...   
3    스포츠/레저  홈트레이닝  보호대/체중계         3.0   
3    스포츠/레저  홈트레이닝  보호대/체중계         3.0   
3    스포츠/레저  홈트레이닝  보호대/체중계         3.0   
3    스포츠/레저  홈트레이닝  보호대/체중계         3.0   
3    스포츠/레저  홈트레이닝  보호대/체중계         3.0   

                                                 내용_x  \
0   ['베이스알파에센셜 신사용 장목 양말 10켤레', '베이스알파 에센셜 고탄력 팬티 ...   
0   ['베이스알파에센셜 신사용 장목 양말 10켤레', '베이스알파 에센셜 고탄력 팬티 ...   
0   ['베이스알파에센셜 신사용 장목 양말 10켤레', '베이스알파 에센셜 고탄력 팬티 ...   
0   ['베이스알파에센셜 신사용 장목 양말 10켤레', '베이스알파 에센셜 고탄력 팬티 ...   
0   ['베이스알파에센셜 신사용 장목 양말 10켤레', '베이스알파 에센셜 고탄력 팬티 ...   
..                                                ...   
3   ['무로 바라나스 종아리 마사지 요가링 2p + 운동 매뉴얼, 혼합 색상', '이고...   
3   ['무로 바라나스 종아리 마사지 요가링 2p + 운동 매뉴얼, 혼합 색상', '이고...   
3   ['무로 바라나스 종아리 마사지 요가링 2p + 운동 매뉴얼, 혼합 색상', '이고...   
3   ['무로 바라나스 종아리 마사지 요가링 2p + 운동 매뉴얼, 혼합 색상', '이고...   
3   ['무로 바라나스 종아리 마사지 요가링 2p + 운동 매뉴얼, 혼합 색상', '이고...   

                                      내용_y  
0                ['베이스알파에센셜 신사용 장목 양말 10켤레  
0            '베이스알파 에센셜 고탄력 팬티 스타킹 20D 10p  
0          '베이스알파에센셜 여성용 베이직 중목 골지 양말 10켤레  
0            '베이스알파 에센셜 여성용 데일리 중목 양말 10켤레  
0                        '루루백 여성용 블루섬 크로스백  
..                                     ...  
3                   '멜킨스포츠 발목스트랩, 튜빙_발목스트랩  
3   'POWER PLUS 테이핑 팔꿈치보호대 남녀고용, 테이핑팔꿈치-블랙  
3                       '바름 압박용 발목 보호대, 1개  
3   '카스 디지털체중계 HE-70 슈퍼화이트, 본상품 선택, 본상품 선택  
3            'AOLIKES 오른쪽 어깨보호대 1697, 1개']  

[984551 rows x 6 columns]

In [9]:
# data = pd.read_csv("C:/Users/ILIFO-034/Desktop/쿠팡/crawling/1.패션의류잡화/가방잡화.csv")
# split = data.내용.str.split("', ")
# st = []
# for i in split:
#     if len(i) >= 10:
#         st.append(i)
# st

In [10]:
dd.drop_duplicates(subset=['내용_y'], inplace=True) # 내용_y 열에서 중복인 내용이 있다면 중복 제거
del dd['중분류']
del dd['대분류']
del dd['내용_x']
del dd['Unnamed: 0']
dd

소분류                                    내용_y
0      여성가방               ['베이스알파에센셜 신사용 장목 양말 10켤레
0      여성가방           '베이스알파 에센셜 고탄력 팬티 스타킹 20D 10p
0      여성가방         '베이스알파에센셜 여성용 베이직 중목 골지 양말 10켤레
0      여성가방           '베이스알파 에센셜 여성용 데일리 중목 양말 10켤레
0      여성가방                       '루루백 여성용 블루섬 크로스백
..      ...                                     ...
3   보호대/체중계                 '후투로 스포츠형 베이직 손목보호대, 1개
3   보호대/체중계                  '멜킨스포츠 발목스트랩, 튜빙_발목스트랩
3   보호대/체중계  'POWER PLUS 테이핑 팔꿈치보호대 남녀고용, 테이핑팔꿈치-블랙
3   보호대/체중계                      '바름 압박용 발목 보호대, 1개
3   보호대/체중계           'AOLIKES 오른쪽 어깨보호대 1697, 1개']

[643400 rows x 2 columns]

In [11]:
dd = dd[dd['내용_y'].notna()]


In [12]:
len(dd['소분류'].unique())

1577

In [13]:
dd.isnull().sum()

소분류     0
내용_y    0
dtype: int64

In [14]:
dd['소분류'].value_counts()

해외직구         1590
분유           1516
영양제          1252
테마의류         1232
상하의 세트       1157
             ... 
자동줄             1
바구니/바스켓         1
주방잡화            1
휴지통/분리수거함       1
캐릭터/아동식기        1
Name: 소분류, Length: 1577, dtype: int64

In [15]:
X = dd['내용_y']
y = dd['소분류']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)
X_train.shape

(482549,)

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train.values.astype('U'))
# x = v.fit_transform(df['Review'].values.astype('U'))

In [123]:
count_vect.vocabulary_

{'내츄레이드': 215039,
 '프로틴': 514779,
 '비건': 312855,
 '쉐이크': 345508,
 '444g': 37442,
 '1개': 17734,
 '미니달콩': 280330,
 '유아동': 414891,
 '메론': 268076,
 '곰니트': 191025,
 '가디건': 173323,
 '쁘띠뮤': 317957,
 '릴리프릴상하세트': 258363,
 '2color': 26637,
 '나홀로': 211686,
 '유럽': 413600,
 '겁쟁이': 183256,
 '원달이의': 408920,
 '번째': 296489,
 '배낭여행': 293129,
 '만화': 262863,
 '231': 23159,
 '프로젝트': 514668,
 '써모스': 363885,
 '에어': 385814,
 '포트': 510350,
 '보온보냉병': 302693,
 '0l': 3600,
 '에어포트': 386391,
 'b001ejnthc': 71312,
 '바나나랜드': 285475,
 '에어팟': 386349,
 '프로': 514340,
 '철가루': 462402,
 '방지': 292484,
 '스티커': 352238,
 '3세트': 35079,
 '단일상품': 226861,
 '투명': 495804,
 'clear': 82429,
 '비비고': 313697,
 '매운왕교자': 264750,
 '385gx2ea': 33086,
 '4세트': 39958,
 '없음': 384414,
 '상세설명': 324416,
 '참조': 459770,
 '새밀린': 325358,
 '강아지': 178723,
 '고양이': 188387,
 '급성만성': 202932,
 '간질환': 176916,
 '보조제': 303114,
 '분말형': 307859,
 '그린트리': 200908,
 '너를': 216002,
 '위한': 412372,
 '디저트': 243068,
 '간식': 176614,
 '오리': 396863,
 '명태': 270621,
 '소프트': 337762

In [21]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_tranformer = TfidfTransformer()
X_train_tfidf = tfidf_tranformer.fit_transform(X_train_counts)
X_train_tfidf.shape

In [20]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tfidf, y_train)

In [18]:
from sklearn.pipeline import Pipeline
text_clf = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('clf',  MultinomialNB()),])
text_clf = text_clf.fit(X_train, y_train)

In [122]:
predicted = text_clf.predict(X_test)
text_clf.score(X_test, y_test)

0.5896549580354368

In [ ]:
predicted

In [15]:
x = pd.DataFrame()
x['x_test'] = X_test
x['predict'] = predicted

In [16]:
x

x_test  predict
13         '생각놀이 느낌놀이 수학익힘 3세:유아 통합 학습 프로그램, 애플비     문학전집
3             '제스프리 유기농 썬골드키위 6입, 550g, 1팩, 실온보관   키위/참다래
0          '작은 아씨들(영화 공식 원작 소설 오리지널 커버), 알에이치코리아     해외직구
7                                       '신약, 인산가     해외직구
4        '싸파 다이니마 골드 P.E 5색 합사줄 0.8호, 150m, 10개입  줄/바늘/채비
..                                           ...      ...
3   'The Company Of Animals 배스커빌 울트라 강아지 입마개, 1개      입마개
1                        '다한수제고가구 BJM9치미니호족반, 단품  찻상/전통소반
2                      '1000 귀여운 복숭아 모모 샤프 - 5자루       샤프
5                                '하우 재중북한이탈여성들의삶       국어
3                                 '21세기 자본, 글항아리   킥판/킥보드

[128680 rows x 2 columns]

In [1]:
predicted = text_clf.predict('제스프리 유기농 썬골드키위 6입, 550g, 1팩, 실온보관')
print(predicted)

키위/참다래


In [124]:
import pickle
with open('nivebayes.pkl', 'wb') as f:
    pickle.dump(text_clf, f)


In [ ]:
from sklearn.linear_model import SGDClassifier 
text_clf = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),                     
                     ('clf', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, random_state=42))]) 
text_clf = text_clf.fit(X_train, y_train) 

In [23]:
predicted = text_clf.predict(X_test)
print(np.mean(predicted == y_test))

0.5960584395399441


In [25]:
y_test.target_names('소분류')

AttributeError: 'Series' object has no attribute 'target_names'

In [31]:
from sklearn import metrics
print(metrics.classification_report( predicted, y_test)) 


C:\Users\ILIFO-034\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                precision    recall  f1-score   support

      3/4도어냉장고       0.70      0.69      0.69       108
     BL(보이즈러브)       0.74      0.44      0.55       199
          BT21       0.55      0.92      0.69        38
       DIY 패키지       0.55      0.55      0.55        89
          DSLR       0.58      0.71      0.64       106
       DSLR 렌즈       0.81      0.60      0.69       143
      IQ퍼즐/스도쿠       0.60      0.60      0.60        20
         LED캔들       0.30      0.74      0.43        38
   LEET:법학적성시험       0.71      0.65      0.68       118
Meet/Deet/Peet       0.94      0.73      0.82       146
    PA/마이크/레코딩       0.64      0.67      0.65       112
    PC타이틀/주변기기       0.46      0.42      0.44       122
  PSAT (행시/외시)       0.88      0.74      0.80       142
     RC드론/쿼드콥터       0.35      0.63      0.45        67
          RC로봇       0.43      0.47      0.45       102
    RC바이크/오토바이       0.53      0.75      0.62        80
      RC보트/잠수함       0.84      0.56      0.67  

In [27]:
 
print(metrics.confusion_matrix(y_test, predicted))

[[ 74   0   0 ...   0   0   0]
 [  0  87   0 ...   0   0   0]
 [  0   0  35 ...   0   0   0]
 ...
 [  0   0   0 ...  43   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0 107]]
